#
# [custom.shell]
# command = "echo $STARSHIP_SHELL"  # shows output of command
# when = """ test "$STARSHIP_SHELL" != "fish" """
# style = "dimmed blue"
# format = "[$output]($style)"
# shell =["bash"]
#
# [custom.neovim]
# command = 'bob ls | rg Used | awk "{print \$2}"'  # shows output of command
# detect_folders = ["lua"]
# style = "green"
# format = "[ $output ]($style)"
# shell =["bash"]
#
#
# [git_status]
# untracked = '[ $count](bold yellow) '
# staged = '[ $count](bold green) '
# stashed = "[ ](cyan) "
# deleted = '[ $count](bold red) '
# modified= '[ $count](bold blue) '
# behind = '[ ](bold purple) '
# ahead = '[ ](bold purple) '
# format = '([$all_status$ahead_behind]($style))'
#
# # [conda]
# # format = '[$symbol$environment](dimmed green) '

[[battery.display]]
threshold = 50

[lua]
detect_folders = []
symbol = " "

[git_metrics]
disabled = false

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "
format = '[$symbol$environment](dimmed green) '

[dart]
symbol = " "

[directory]
truncation_symbol = '…/'
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "


[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
openSUSE = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = "🪺 "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

