# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family      Hurmit Nerd Font Mono
bold_font        auto
italic_font      Victor Mono Medium Italic Nerd Font Complete
bold_italic_font Victor Mono Bold Italic Nerd Font Complete

font_size 14.0

# modify_font cell_height 2px

#: }}}


#: settings{{{

confirm_os_window_close 0

enable_audio_bell no

tab_bar_style powerline
tab_separator " "

copy_on_select yes

tab_bar_edge top

cursor_shape block
shell_integration no-cursor

enabled_layouts Splits,Stack

#: }}}



#: Keyboard shortcuts {{{

kitty_mod cmd+shift

# cmd+t new tab
# cmd+w close tab
map kitty_mod+l next_tab
map kitty_mod+h previous_tab

# cmd+shit+d close window
# cmd+r resize the window
map kitty_mod+enter launch --location=split --cwd=current
map kitty_mod+\ launch --location=vsplit    --cwd=current
map kitty_mod+minus launch --location=hsplit --cwd=currentt

map kitty_mod+left neighboring_window left
map kitty_mod+right neighboring_window right
map kitty_mod+up neighboring_window up
map kitty_mod+down neighboring_window down

#: }}}


# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
